# Generated by Django 2.2.13 on 2020-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0092_reservationcancelreason_reservationcancelreasoncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationcancelreason',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservationcancelreasoncategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservationcancelreasoncategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservationcancelreasoncategory',
            name='description_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservationcancelreasoncategory',
            name='description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
